### ISSUE TITLE
[BUG] Engineer cannot upgrade friendly buildings under some circumstances

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#10]
https://user-images.githubusercontent.com/87569823/155362018-7f43b9ed-8e78-4855-8b98-1254b05847f2.mov

I suspect this issue might have something to do with:
It wasn't my building
Some issue with wrench modes
The guy was using gunslinger before he switched to a wrench and built a dispenser
Or maybe its a server thing idk

**Comment by kingofings** [comment]
I need more info on this Step by Step recreation. Otherwise i have no way of debugging really what's causing it (Video preferred, POV of both parties)

**Comment by Pepsi-Man-TF2** [comment]
i havent found another instance of this an it has seemed to resolve itself

**Comment by kingofings** [comment]
Instances of this happening in MvM. Suspect plugin thinks the building has modded props even though it does not thus preventing upgrading

**Comment by kingofings** [comment]
Probably fixed since we completely removed the non upgradable part of the code since we mark the amp as a minibuilding now. Will be pushed in next update
