### ISSUE TITLE
[BUG] Rescue range clip resupply downside bypass

### ISSUE THREAD

**Issue by Pudding555** [kingofings/ktbm-bugtracker#12]
**Description**
Refreshing your loadout ignores the Rescue Ranger's downside of not having its clip be refilled with resupply cabinets

**To Reproduce**
https://www.youtube.com/watch?v=8vxWNaSddy4
1. Be in the spawn
2. Use bolts from your Rescue Ranger clip
3. Use a refresh loadout bind (bind KEY "load_itempreset 0")
4. You will have your full clip restored

**Expected behavior**
Refreshing your loadout would still make it so you would need to reload with the Rescue Ranger

**Additional context**
Refreshing your loadout is in most maps even more effective than going in all the way to the back of the spawn to touch the resupply cabinet and then come back to heal your sentry

**Comment by kingofings** [comment]
Fixed
