### ISSUE TITLE
[BUG] Killsound playing without destroying gunslinger buildings

### ISSUE THREAD

**Issue by Pudding555** [kingofings/ktbm-bugtracker#14]
**Describe the bug**
After dealing an significant amount of damage to an Amplifier or Boost/Jump Pad the killsound will play without it being destroyed, if the building in question was an Amplifier it will return back to the default Dispenser model

**To Reproduce**
1. Shoot an Amplifier or Boost/Jump Pad until it's almost dead.
2. Killsound you will play without it being destroyed.

**Expected behavior**
Play the kill sound only when the building is destroyed and have Amplifiers not revert back to the Dispenser model.

**Additional context**
The exact amount of damage to trigger the killsound is unknown.

https://user-images.githubusercontent.com/105569710/174455890-f4e58050-b0ac-46c6-9c53-91a2763e3924.mp4

**Comment by kingofings** [comment]
The amplifier turning back is a bug.

The killsound player is a general bug from tf2 and not ktbm specific.

This currently has low priority

**Comment by kingofings** [comment]
amp changing model should be fixed and pushed in the next update
