### ISSUE TITLE
[BUG] Incorrect Gas Passer Meter Behaviour

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#18]
Upon death the gas passer meter does not restart as empty.

I dont know if this information is valuable but respawn took about 19 seconds (i alt-tabbed), maybe this is an issue with how the gas passer meter used to work in vanilla.

https://user-images.githubusercontent.com/87569823/178353796-737f8985-1682-4c5b-ae31-1387a5eab013.mov

**Comment by kingofings** [comment]
This seems rather like a quirk from tf2 itself. Needs retesting

**Comment by Pepsi-Man-TF2** [comment]
for any clarification, you retain the meter you had at the point of death.

**Comment by kingofings** [comment]
This is default tf2 behaviour
