### ISSUE TITLE
List of Non-Compatible Maps for Bots

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#19]
Figured it was appropriate to note these down and add to it so when the time comes they can eventually be fixed.

**A list of maps in which server bots have been observed to have major navigation/ behavioural issues:**

koth_ramjam_rc1

**Comment by kingofings** [comment]
Nav meshes are auto generated and not hand made. Consider contirbuting improved nav meshes.
