### ISSUE TITLE
[BUG] Ambassador Damage Inconsistencies

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#20]
https://user-images.githubusercontent.com/87569823/178600682-be94c29c-3934-4a2f-bdc0-c2f2d945cba2.mov

Can sometimes do over 102 headshot damage at what i believe are closer ranges. I'm not sure what could be causing this?

**Comment by kingofings** [comment]
The demoman and soldier had a bullet damage vulnerability from the pain train.

**Comment by Pepsi-Man-TF2** [comment]
but that's a flat 10% damage vulnerability, shouldn't a headshot have dealt 112 damage?
