### ISSUE TITLE
[BUG] Upgrading buildings visual and HUD issues

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#3]
When upgrading a building using any wrench, the building appears to be dead, the building remains intact (still functioning) and has no hp on the HUD.

https://user-images.githubusercontent.com/87569823/142771581-87066fa4-c73b-4593-b1f0-6e4cd1dd7ca6.mov

**Comment by kingofings** [comment]
From what I've tested it seems to be an issue with the isolated wrench modes attributes. Will look into it.

Thanks for reporting.

**Comment by kingofings** [comment]
Fixed as of now
