### ISSUE TITLE
[BUG] Mysterious Bonk and Cola Bugs

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#30]
Noted by Pudding but was fixed when they reconnected, I did not have this issue at all.

https://youtu.be/8f2xxWx_9Dg
small vid they made of what they experienced

Appears to be able to activate colas endlessly, I'm short for details here given that i haven't had this issue myself.

**Comment by kingofings** [comment]
This seems more like a oneoff thing retest needed.

**Comment by kingofings** [comment]
Was caused by stock bat custom attribute for faster secondary recharge rate
