### ISSUE TITLE
Medic bots bypassing vaccinator charge requirement. 

### ISSUE THREAD

**Issue by houseofgit** [kingofings/ktbm-bugtracker#31]
Bot medics using the vaccinator inherit the vanilla stats over the KTBM balances.

Reproduce via this process.
1. Open up a KTBM casual server, vote yes on bots. Try this until a vaccinator medic spawns. If you have access to administrative commands, just spawn in one.
2. Issue should become obvious.

The vaccinator should use the stats it has in vanilla over modded stats. 

Discovered during a game, medic bots running the vaccinator would prove far more effective/annoying than the stats given to them via the mod should allow.

**Comment by kingofings** [comment]
Please refrain from explaining issues with "Issue should become obvious" and focus more on actually finding the underlying issue. Thank you.
