### ISSUE TITLE
[BUG] MVM Infinite Money 2

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#35]
Still able to do this with the targe

**Comment by Pepsi-Man-TF2** [comment]
(and millk too apparently)

**Comment by kingofings** [comment]
@TrickyTrix935  Any update?

**Comment by TrickyTrix935** [comment]
Targe and milk corrected, also found one instance with the quick fix. 
Fix will be rolled out in the next update

**Comment by kingofings** [comment]
@TrickyTrix935 Please keep issues opened if they are fixed and mark them as so until the fix is pushed
