### ISSUE TITLE
Tide turner crits

### ISSUE THREAD

**Issue by Pepsi-Man-TF2** [kingofings/ktbm-bugtracker#4]
tide turner does critical damage at the end of its charge, reminder for kingo

https://user-images.githubusercontent.com/87569823/145690021-1de84d98-015b-47ee-aae1-160c0b396aa3.mov

**Comment by kingofings** [comment]
This issue occoured because of a configuration error and should work as intended now. Clientside prediction errors on the animation may still occour due to high ping.
