### ISSUE TITLE
[BUG] Family Business's primary reserve ammo penalty nullified by switching classes.

### ISSUE THREAD

**Issue by explosive-06** [kingofings/ktbm-bugtracker#6]
**Description**
While having the FB equipped in the 4th slot, one can switch to certain classes and switch back to Heavy, once done the minigun's ammo will be 200 as opposed to the expected 20 (50 if you switched to medic)

**To Reproduce**
1. Equip the Family Business in the 4th slot
2. Switch to any class
3. Switch back to Heavy

**Expected behavior**
Minigun ammo should be 20. Though it seems the ammo goes back to 20 if you resupply.

**Video footage**
https://user-images.githubusercontent.com/79483871/146622324-ba99c2d2-c0ea-460e-a0bd-4f4a987f9535.mp4

**It is worth noting that this doesn't happen if the FB is equipped in the 2nd slot**
https://user-images.githubusercontent.com/79483871/146622424-09ddcc14-8ca2-4f6e-b4de-d626f21e6513.mp4

**Comment by kingofings** [comment]
Fixed as of now
