### ISSUE TITLE
[BUG] Soda Popper's New Hype not increasing jump height.

### ISSUE THREAD

**Issue by explosive-06** [kingofings/ktbm-bugtracker#7]
**Description**
When activating the hype mode with the soda popper, the jump height doesn't seem increased at all, or at least not as high as seen in the preview here: https://discord.com/channels/132349439506382848/418120895970934795/928464979722641439

Footage:

https://user-images.githubusercontent.com/79483871/149638441-f19544c5-6770-46f7-bd77-75ccfa7c717b.mp4

**Additional context**
Dang kingo there was no need to do me like that at the end of the video lol.

**Comment by kingofings** [comment]
fixed
