### ISSUE TITLE
[BUG] Pyro being Marked For Death for a short instant upon using his jetpack.

### ISSUE THREAD

**Issue by explosive-06** [kingofings/ktbm-bugtracker#8]
**Description**
As the title suggests, upon activating the thermal thruster (more specifically, while doing the little bounce before launching), the Pyro is marked for death. My own speculation as to why this happens is that ktbm's "MfD while the parachute is deployed" downside for the BASE Jumper is applying to the jetpack as well since it seems to be using the same effect for the bounce. Not sure if this helps at all but I just wanted to share my thoughts nonetheless.

https://user-images.githubusercontent.com/79483871/149641691-7e098ba0-797a-4941-a050-f85e59d6ad82.mp4

**Comment by kingofings** [comment]
fixed
